version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      -   /mnt/f/devops/cicd/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
    volumes:
      - /mnt/f/devops/cicd/grafana-storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
   name: monitoring

volumes:
  grafana-storage: